### ISSUE TITLE
Add keywords for SCM to appear via Registry search

### ISSUE THREAD

**Issue by zbuchheit** [pulumi/registry#5372] opened 2024-09-10 20:23 UTC
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Currently, if you search for "SCM", "PaloAlto", or "Palo Alto" in the Registry search, the [SCM provider](https://www.pulumi.com/registry/packages/scm/) doesn't show as a result

### Example
![Image](https://github.com/user-attachments/assets/13d4252c-0713-49e2-b8da-867d458c93c1)

### Affected area/feature

Registry Search

**Comment by sean1588** [comment] 2024-09-25 17:59
@zbuchheit - our filter on the registry search is actually really basic right now and is mostly based on text matching of the package titles. These titles are actually sourced from the `displayName` property in the provider's schema file. I notice this provider is bridged, so not sure if you all have control over the display name or if that is set automatically based on some upstream tf provider config. If you have some way to get that updated to contain SCM and Pal Alto, then the search should start working the next time you release the provider.

**Comment by iwahbe** [comment] 2024-11-14 07:50
Closing as a duplicate of https://github.com/pulumi/registry/issues/4902.

**Closed by iwahbe** 2024-11-14 07:50 UTC
Labels: kind/bug, resolution/duplicate, area/search
