### ISSUE TITLE
Fix of a syntax error in a service account code example

### ISSUE THREAD

**Issue by snamber** [pulumi/registry#758] opened 2022-03-19 18:43 UTC
File: [themes/default/content/registry/packages/gcp/api-docs/serviceAccount/account/_index.md](https://www.pulumi.com/registry/packages/gcp/api-docs/serviceaccount/account/)

The imported module "serviceAccount" needs to be lowercase to work: "serviceaccount"

Now it is
```go
package main

import (
	"github.com/pulumi/pulumi-gcp/sdk/v6/go/gcp/serviceAccount"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {
		_, err := serviceAccount.NewAccount(ctx, "serviceAccount", &serviceAccount.AccountArgs{
			AccountId:   pulumi.String("service-account-id"),
			DisplayName: pulumi.String("Service Account"),
		})
		if err != nil {
			return err
		}
		return nil
	})
}
```

It should be
```go
package main

import (
	"github.com/pulumi/pulumi-gcp/sdk/v6/go/gcp/serviceaccount"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {
		_, err := serviceaccount.NewAccount(ctx, "serviceAccount", &serviceaccount.AccountArgs{
			AccountId:   pulumi.String("service-account-id"),
			DisplayName: pulumi.String("Service Account"),
		})
		if err != nil {
			return err
		}
		return nil
	})
}
```

**Comment by susanev** [comment] 2022-03-19 21:15
thx for the report!

a few related issues
- https://github.com/pulumi/pulumi-gcp/issues/722
- https://github.com/pulumi/pulumi-hugo/issues/477

im going to close out the pulumi-hugo one as a dupe, since it doesn't make much sense for it to be in that repo anymore.

**Comment by susanev** [comment] 2022-05-13 14:36
it was noted in community slack, that `serviceAccount` 404s, from the left nav of the gcp API docs

**Comment by jkodroff** [comment] 2022-05-14 19:58
Duplicate of https://github.com/pulumi/pulumi-gcp/issues/722

**Comment by jkodroff** [comment] 2022-05-26 21:25
@susanev Removing from your board because the root issue is we have the namespace incorrect in the provider. This is a breaking change, so we will need to wait until the next major release of pulumi-gcp to fix.

**Comment by susanev** [comment] 2022-06-02 15:38
thank you!

**Comment by mnlumi** [comment] 2023-10-26 20:20
Duplicate of https://github.com/pulumi/pulumi-gcp/issues/722

**Closed by mnlumi** 2023-10-26 20:20 UTC
Labels: kind/bug, resolution/duplicate, blocked
