### ISSUE TITLE
vmware lookup arguments incorrect

### ISSUE THREAD

**Issue by jaxxstorm** [pulumi/registry#464] opened 2021-12-15 21:40 UTC
The example here: https://www.pulumi.com/registry/packages/vsphere/api-docs/getvirtualmachine/

In the Go programming language, doesn't compile correctly. For posterity:

## Incorrect
```go
package main

import (
	"github.com/pulumi/pulumi-vsphere/sdk/v4/go/vsphere"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {
		opt0 := "dc1"
		datacenter, err := vsphere.LookupDatacenter(ctx, &GetDatacenterArgs{
			Name: &opt0,
		}, nil)
		if err != nil {
			return err
		}
		opt1 := datacenter.Id
		_, err = vsphere.LookupVirtualMachine(ctx, &GetVirtualMachineArgs{
			DatacenterId: &opt1,
			Name:         "test-vm-template",
		}, nil)
		if err != nil {
			return err
		}
		return nil
	})
}
```

## Correct

```go
package main

import (
	"github.com/pulumi/pulumi-vsphere/sdk/v4/go/vsphere"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {
		opt0 := "a-dc"
		datacenter, err := vsphere.LookupDatacenter(ctx, &vsphere.LookupDatacenterArgs{
			Name: &opt0,
		}, nil)
		if err != nil {
			return err
		}
		opt1 := datacenter.Id
		_, err = vsphere.LookupVirtualMachine(ctx, &vsphere.LookupVirtualMachineArgs{
			DatacenterId: &opt1,
			Name:         "a-vm",
		}, nil)
		if err != nil {
			return err
		}
		return nil
	})
}
```

**Comment by leezen** [comment] 2021-12-18 03:48
Closing as a dupe of https://github.com/pulumi/docs/issues/6853

**Closed by leezen** 2021-12-18 03:48 UTC
Labels: kind/bug, resolution/duplicate
