### ISSUE TITLE
AWS IAM policy role

### ISSUE THREAD

**Issue by JonathanBernaerts** [pulumi/registry#3057] opened 2023-08-24 07:36 UTC
File: [themes/default/content/registry/packages/aws/api-docs/iam/role/_index.md](https://www.pulumi.com/registry/packages/aws/api-docs/iam/role/)

Hi, we found out that when creating an aws role with inline policy, it shows the changes when previewing but when applying it does no changes. I'm talking about the parameter [inline_policies](https://www.pulumi.com/registry/packages/aws/api-docs/iam/role/#inline_policies_python).

**Comment by interurban** [comment] 2023-08-24 22:36
Thank you for catching this and submitting an issue @JonathanBernaerts ; we'll take a look.

**Comment by toriancrane** [comment] 2023-09-18 11:53
Hi @JonathanBernaerts,

Thank you for submitting this issue!

I was unfortunately unable to reproduce this issue. As a reference, I created and deployed the following simple IAM role:

```
import pulumi
import json
import pulumi_aws as aws

test_role = aws.iam.Role("testRoleDebug",
    assume_role_policy=json.dumps({
        "Version": "2012-10-17",
        "Statement": [{
            "Action": "sts:AssumeRole",
            "Effect": "Allow",
            "Sid": "",
            "Principal": {
                "Service": "ec2.amazonaws.com",
            },
        }],
    }),
    tags={
        "tag-key": "tag-value",
    })
```
I then updated this resource with an inline policy as shown here:

```
import pulumi
import json
import pulumi_aws as aws

test_role = aws.iam.Role("testRoleDebug",
    assume_role_policy=json.dumps({
        "Version": "2012-10-17",
        "Statement": [{
            "Action": "sts:AssumeRole",
            "Effect": "Allow",
            "Sid": "",
            "Principal": {
                "Service": "ec2.amazonaws.com",
            },
        }],
    }),
    inline_policies=[
        aws.iam.RoleInlinePolicyArgs(
            name="my_inline_policy",
            policy=json.dumps({
                "Version": "2012-10-17",
                "Statement": [{
                    "Action": ["ec2:Describe*"],
                    "Effect": "Allow",
                    "Resource": "*",
                }],
            }),
        )
    ],
    tags={
        "tag-key": "tag-value",
    })
```
As I am unsure if this workflow mimics your deployment experience, would you mind providing the steps you took/code you used to reproduce this issue?

Also, in reference to the following:

> when applying it does no changes

To clarify, did you mean that the IAM role resource was not updated with the new policy, that the update to the role was not shown in the CLI output, or something else?

Thanks in advance!

**Comment by toriancrane** [comment] 2023-10-18 15:54
Closing due to not being able to reproduce the issue.

**Closed by toriancrane** 2023-10-18 15:54 UTC
Labels: kind/bug, area/docs, awaiting-feedback
