### ISSUE TITLE
api docs filter adds pages that do not exist

### ISSUE THREAD

**Issue by susanev** [pulumi/registry#733] opened 2022-03-14 13:30 UTC
## overview
the api docs filter adds pages when you filter that do not exist
this was reported in kubernetes, but i did not yet check if this occurs elsewhere

this was originally reported in community slack
<img width="346" alt="Screen Shot 2022-03-14 at 6 28 12 AM" src="https://user-images.githubusercontent.com/5489125/158181586-c3a1d3ae-6b03-49b9-ab63-093f58e962f7.png">

### video
https://user-images.githubusercontent.com/5489125/158181911-4bdb925f-730c-49fb-aed2-c4e21a1f5469.mp4

## repro steps
- navigate to kubernetes/api-docs
- scan the left nav notice what is in apiregistration > v1
- now search for service account and watch that list of pages change
- all those new pages you see now 404

**Comment by susanev** [comment] 2022-03-14 13:59
from Evan...

>There is probably a bug in the node cache, or the code that computes and addresses unique path names of nodes. Notice that the two v1 sub-trees are the union of apiregistration/v1 and core/v1. However, apiregistration/v1beta1 is correct.

**Comment by cnunciato** [comment] 2022-03-14 17:11
Possibly a dupe of of https://github.com/pulumi/registry/issues/435.

**Closed** 2022-03-14 20:24 UTC
Labels: resolution/fixed, kind/bug, p1, customer/feedback, emergent
