### ISSUE TITLE
Support self-service in registry

### ISSUE THREAD

**Issue by anita-trimbur** [pulumi/registry#707] opened 2022-03-07 16:32 UTC
## Design Components
- Self-service portal
    - Input collected from contributors (other information, like category, is collected as metadata)
        - Name
        - URL 
        - Publisher
- Loading state
- Failed request message

## Product Considerations
- To what extent can we trust the resources being published? What kind of vetting process is feasible?
    - Can we turn off the auto-merges for the PRs? If we do, whose responsibility would it be to review them? 
    - How can we remove things from the Registry if it shouldn’t be there?
- Is it necessary to require contributors to create Pulumi accounts? How can accounts be accessed inside the Registry?

**Comment by iwahbe** [comment] 2024-11-01 17:33
Closing as a duplicate of #206.

**Closed by iwahbe** 2024-11-01 17:33 UTC
Labels: kind/enhancement, resolution/duplicate
