### ISSUE TITLE
dropletId type mismatch: Droplet returns Output<string> but ReservedIpAssignment requires Input<number>

### ISSUE THREAD

**Issue by beorn** [pulumi/registry#2126] opened 2023-03-01 01:01 UTC
File: [themes/default/content/registry/packages/digitalocean/api-docs/reservedipassignment/_index.md](https://www.pulumi.com/registry/packages/digitalocean/api-docs/reservedipassignment/)

The droplet's id type doesn't match, so you cannot pass the output of a newly created droplet's id to ReservedIpAssignment as shown in the example.  The example doesn't work.

```
Error TS2322: Type 'Output<string>' is not assignable to type 'Input<number>'.
Type 'Output<string>' is not assignable to type 'OutputInstance<number>'.
```

**Comment by lukehoban** [comment] 2023-03-05 21:34
Duplicate of https://github.com/pulumi/pulumi-terraform-bridge/issues/352 (and https://github.com/pulumi/pulumi-digitalocean/issues/256).

**Closed by lukehoban** 2023-03-05 21:34 UTC
Labels: kind/bug, resolution/duplicate

**Comment by beorn** [comment] 2023-03-05 23:23
If this is expected behavior or won't be fixed soon (the collection issue is from June 2021), then maybe the example/docs should be updated with a workaround or note or something?
